### PR TITLE
Fixing proxy list fetch and some other enhancements

### PR DESCRIPTION
**Pull request by tdopires**
Hey @williamokano, nice to meet you! 👋 

I'm maintaining a fork of your repo since may/2018, because I'm with an [open-source Android app for checking MtG deck prices](https://github.com/tdopires/spellnet-android).
I'm sorry for not reaching out to you before with a PR, but here I go!

This PR may have a lot of changes, so I recommend you review by each commit. 
They include:
- Fixing proxy list fetch: checkerproxy.net had changed their API a little bit
- Improvements on LigaMagic card prices: we had just major price, now we also have medium and minimum prices
- Bugfix on card fetch: some LigaMagic card names returned more than one result for the previous URL we're using [(check here)](https://github.com/williamokano/magic-card-prices/commit/0bb56223e9f8769742140933e6096293c24abadc)
- Bugfix on proxy usage: I guess the proxy it wasn't being used before since we didn't used `proxyUrl` from `requestp`, but I'm not sure

Please review carefully and feel free to suggest code improvements, since I'm not exactly an experient NodeJS developer 😅

### CODE REVIEW

**Comment by williamokano** [comment]
Hey @tdopires, thanks a lot for this PR. If you want, I can add you as maintainer of this repo, but you rather choose to keep your own fork, it's fine for me.

Thanks a lot for fixing the broken stuff, I'm not a very good (nodejs) developer and this code is pretty old already 😂😂😂

Merged.

Also, congrats on your opensource app, it seems amazing, and I always cheer for people who are willing to do opensource stuff.

**Comment by tdopires** [comment]
Thanks @williamokano ! 
I'll keep the fork for now, but I'll let you know if I have any news in the future... (maybe a rewrite to Kotlin 👀)

And if you want to use/test my app, just let me know! 😅

**Comment by williamokano** [comment]
To be honest I was thinking about rewriting it in Kotlin today 😂😂😂, but using spring instead of ktor.

About testing your app, today I was on vacation, so I took the day to learn a little bit of flutter because of your project indeed. 😂

**Comment by tdopires** [comment]
Hey @williamokano , if you don't mind you... Could you add a "hacktoberfest-accepted" label to this PR?
I'm participating of the [Hacktoberfest event from Digital Ocean](https://hacktoberfest.digitalocean.com/), and with the label I think it will count to my contribution progress on the event...

**Comment by williamokano** [comment]
Sure, done.

**Pull request merged**
